name: 'Test ImpressCMS addon'
description: 'About GitHub action that tries to help to test ImpressCMS addon'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'check'
  color: 'gray-dark'

inputs:
  impresscms_version:
    description: "ImpressCMS version tag to test addon with"
    default: v2.0.x
    required: false
  addon_type:
    description: "Type of ImpressCMS addon"
    required: false
  php_version:
    description: "PHP version to use"
    default: "7.4"
    required: false
  composer_version:
    description: "PHP composer version to use for test"
    default: "2"
    required: false
  post_max_size:
    description: "Max post file size"
    default: 256M
    required: false
  extra_php_extensions:
    description: "Extra comma separated extra PHP extensions list that is required by addon"
    default: ""
    required: false
  mysql_version:
    description: "MySQL version to use"
    default: "8.0"
    required: false

runs:
  using: 'composite'

  steps:
    - name: Configuring...
      id: config
      run: |
        bash ${{ github.action_path }}/bin/icms-path.sh
        bash ${{ github.action_path }}/bin/addon-info.sh "${{ inputs.addon_type }}"
        bash ${{ github.action_path }}/bin/unused-port.sh mysql
      shell: bash

    - name: Installing PHP...
      uses: shivammathur/setup-php@2.3.1
      with:
        php-version: ${{ inputs.php_version }}
        extensions: curl, gd, pdo_mysql, json, mbstring, pcre, session, ${{ inputs.extra_php_extensions }}
        ini-values: post_max_size=${{ inputs.post_max_size }}
        coverage: none
        tools: composer:v${{ inputs.composer_version }}

    - name: Starting MySQL server...
      uses: addnab/docker-run-action@v3
      with:
        image: mysql:${{ inputs.mysql_version }}
        options: -d -p ${{ steps.config.outputs.mysql_port }}:3306 -e MYSQL_ROOT_PASSWORD=icms -e MYSQL_DATABASE=icms --name mysql_server_${{ steps.config.outputs.mysql_port }}

    - name: Creating ImpressCMS project...
      run: |
        bash ${{ github.action_path }}/bin/create-project.sh \
          "${{ steps.config.outputs.icms_path }}" \
          ${{ inputs.impresscms_version }}
      shell: bash

    - name: Installing ImpressCMS...
      id: install_icms
      uses: impresscms-dev/install-impresscms-action@v0.1.1
      with:
        database_name: icms
        database_user: root
        database_password: icms
        database_port: ${{ steps.config.outputs.mysql_port }}
        database_prefix: icms
      working-directory: ${{ steps.config.outputs.icms_path }}

    - name: Adding local composer repo...
      run: bash ${{ github.action_path }}/bin/new-local-repo.sh "${{ steps.config.outputs.icms_path }}"
      shell: bash

    - name: Installing legacy addon...
      run: |
        bash ${{ github.action_path }}/bin/install-legacy-addon.sh \
          "${{ steps.config.outputs.addon_type }}" \
          "${{ steps.config.outputs.addon_dir }}" \
          "${{ steps.config.outputs.addon_install_path }}"
      shell: bash
      if: steps.config.outputs.addon_installation_type == 'legacy'

    - name: Installing composer {{ inputs.addon_type }}...
      run: composer require ${{ steps.config.outputs.addon_name }}
      shell: bash
      if: steps.config.outputs.addon_installation_type == 'composer'
      working-directory: ${{ steps.config.outputs.icms_path }}

    - name: Testing with PHPUnit
      run: |
        bash ${{ github.action_path }}/bin/test.sh \
          ${{ steps.config.outputs.mysql_port }} \
          "${{ steps.config.outputs.addon_install_path }}"
      shell: bash
      working-directory: ${{ steps.config.outputs.icms_path }}
      if: ${{ steps.config.outputs.addon_test_path }} != ''

    - name: Updating addon...
      run: php bin/console {{ inputs.addon_type }}:update ${{ steps.config.outputs.addon_dir }}
      shell: bash
      working-directory: ${{ steps.config.outputs.icms_path }}

    - name: Uninstalling addon...
      run: php bin/console {{ inputs.addon_type }}:uninstall ${{ steps.config.outputs.addon_dir }}
      shell: bash
      working-directory: ${{ steps.config.outputs.icms_path }}

    - name: Stopping MySQL server...
      run: docker rm --force mysql_server_${{ steps.config.outputs.mysql_port }}
      shell: bash
      continue-on-error: true

    - name: Deleting temp folder...
      run: rm -rf "${{ steps.config.outputs.icms_path }}" || true
      shell: bash
      continue-on-error: true